/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenant_idRouteImport } from './routes/t.$tenant_id'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as TTenant_idTeamRouteImport } from './routes/t.$tenant_id/team'
import { Route as TTenant_idDashboardRouteImport } from './routes/t.$tenant_id/dashboard'
import { Route as TTenant_idAnalyticsRouteImport } from './routes/t.$tenant_id/analytics'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite.$token'
import { Route as TTenant_idRulesIndexRouteImport } from './routes/t.$tenant_id/rules/index'
import { Route as TTenant_idProjectsIndexRouteImport } from './routes/t.$tenant_id/projects/index'
import { Route as TTenant_idApprovalsIndexRouteImport } from './routes/t.$tenant_id/approvals/index'
import { Route as TTenant_idSettingsNotificationsRouteImport } from './routes/t.$tenant_id/settings/notifications'
import { Route as TTenant_idSettingsGeneralRouteImport } from './routes/t.$tenant_id/settings/general'
import { Route as TTenant_idSettingsBillingRouteImport } from './routes/t.$tenant_id/settings/billing'
import { Route as TTenant_idSettingsAccountRouteImport } from './routes/t.$tenant_id/settings/account'
import { Route as TTenant_idRulesNewRouteImport } from './routes/t.$tenant_id/rules/new'
import { Route as TTenant_idProjectsNewRouteImport } from './routes/t.$tenant_id/projects/new'
import { Route as TTenant_idApprovalsRequest_idRouteImport } from './routes/t.$tenant_id/approvals/$request_id'
import { Route as TTenant_idProjectsProject_idIndexRouteImport } from './routes/t.$tenant_id/projects/$project_id/index'
import { Route as TTenant_idRulesRule_idEditRouteImport } from './routes/t.$tenant_id/rules/$rule_id.edit'
import { Route as TTenant_idProjectsProject_idApiKeysRouteImport } from './routes/t.$tenant_id/projects/$project_id/api-keys'

const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenant_idRoute = TTenant_idRouteImport.update({
  id: '/t/$tenant_id',
  path: '/t/$tenant_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const TTenant_idTeamRoute = TTenant_idTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idDashboardRoute = TTenant_idDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idAnalyticsRoute = TTenant_idAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TTenant_idRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRoute,
} as any)
const TTenant_idRulesIndexRoute = TTenant_idRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idProjectsIndexRoute = TTenant_idProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idApprovalsIndexRoute =
  TTenant_idApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idSettingsNotificationsRoute =
  TTenant_idSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idSettingsGeneralRoute =
  TTenant_idSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idSettingsBillingRoute =
  TTenant_idSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idSettingsAccountRoute =
  TTenant_idSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idRulesNewRoute = TTenant_idRulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idProjectsNewRoute = TTenant_idProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => TTenant_idRoute,
} as any)
const TTenant_idApprovalsRequest_idRoute =
  TTenant_idApprovalsRequest_idRouteImport.update({
    id: '/approvals/$request_id',
    path: '/approvals/$request_id',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idProjectsProject_idIndexRoute =
  TTenant_idProjectsProject_idIndexRouteImport.update({
    id: '/projects/$project_id/',
    path: '/projects/$project_id/',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idRulesRule_idEditRoute =
  TTenant_idRulesRule_idEditRouteImport.update({
    id: '/rules/$rule_id/edit',
    path: '/rules/$rule_id/edit',
    getParentRoute: () => TTenant_idRoute,
  } as any)
const TTenant_idProjectsProject_idApiKeysRoute =
  TTenant_idProjectsProject_idApiKeysRouteImport.update({
    id: '/projects/$project_id/api-keys',
    path: '/projects/$project_id/api-keys',
    getParentRoute: () => TTenant_idRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-team': typeof CreateTeamRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/t/$tenant_id': typeof TTenant_idRouteWithChildren
  '/invite/$token': typeof AuthInviteTokenRoute
  '/t/$tenant_id/analytics': typeof TTenant_idAnalyticsRoute
  '/t/$tenant_id/dashboard': typeof TTenant_idDashboardRoute
  '/t/$tenant_id/team': typeof TTenant_idTeamRoute
  '/t/$tenant_id/approvals/$request_id': typeof TTenant_idApprovalsRequest_idRoute
  '/t/$tenant_id/projects/new': typeof TTenant_idProjectsNewRoute
  '/t/$tenant_id/rules/new': typeof TTenant_idRulesNewRoute
  '/t/$tenant_id/settings/account': typeof TTenant_idSettingsAccountRoute
  '/t/$tenant_id/settings/billing': typeof TTenant_idSettingsBillingRoute
  '/t/$tenant_id/settings/general': typeof TTenant_idSettingsGeneralRoute
  '/t/$tenant_id/settings/notifications': typeof TTenant_idSettingsNotificationsRoute
  '/t/$tenant_id/approvals/': typeof TTenant_idApprovalsIndexRoute
  '/t/$tenant_id/projects/': typeof TTenant_idProjectsIndexRoute
  '/t/$tenant_id/rules/': typeof TTenant_idRulesIndexRoute
  '/t/$tenant_id/projects/$project_id/api-keys': typeof TTenant_idProjectsProject_idApiKeysRoute
  '/t/$tenant_id/rules/$rule_id/edit': typeof TTenant_idRulesRule_idEditRoute
  '/t/$tenant_id/projects/$project_id/': typeof TTenant_idProjectsProject_idIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-team': typeof CreateTeamRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/t/$tenant_id': typeof TTenant_idRouteWithChildren
  '/invite/$token': typeof AuthInviteTokenRoute
  '/t/$tenant_id/analytics': typeof TTenant_idAnalyticsRoute
  '/t/$tenant_id/dashboard': typeof TTenant_idDashboardRoute
  '/t/$tenant_id/team': typeof TTenant_idTeamRoute
  '/t/$tenant_id/approvals/$request_id': typeof TTenant_idApprovalsRequest_idRoute
  '/t/$tenant_id/projects/new': typeof TTenant_idProjectsNewRoute
  '/t/$tenant_id/rules/new': typeof TTenant_idRulesNewRoute
  '/t/$tenant_id/settings/account': typeof TTenant_idSettingsAccountRoute
  '/t/$tenant_id/settings/billing': typeof TTenant_idSettingsBillingRoute
  '/t/$tenant_id/settings/general': typeof TTenant_idSettingsGeneralRoute
  '/t/$tenant_id/settings/notifications': typeof TTenant_idSettingsNotificationsRoute
  '/t/$tenant_id/approvals': typeof TTenant_idApprovalsIndexRoute
  '/t/$tenant_id/projects': typeof TTenant_idProjectsIndexRoute
  '/t/$tenant_id/rules': typeof TTenant_idRulesIndexRoute
  '/t/$tenant_id/projects/$project_id/api-keys': typeof TTenant_idProjectsProject_idApiKeysRoute
  '/t/$tenant_id/rules/$rule_id/edit': typeof TTenant_idRulesRule_idEditRoute
  '/t/$tenant_id/projects/$project_id': typeof TTenant_idProjectsProject_idIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/create-team': typeof CreateTeamRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/t/$tenant_id': typeof TTenant_idRouteWithChildren
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/t/$tenant_id/analytics': typeof TTenant_idAnalyticsRoute
  '/t/$tenant_id/dashboard': typeof TTenant_idDashboardRoute
  '/t/$tenant_id/team': typeof TTenant_idTeamRoute
  '/t/$tenant_id/approvals/$request_id': typeof TTenant_idApprovalsRequest_idRoute
  '/t/$tenant_id/projects/new': typeof TTenant_idProjectsNewRoute
  '/t/$tenant_id/rules/new': typeof TTenant_idRulesNewRoute
  '/t/$tenant_id/settings/account': typeof TTenant_idSettingsAccountRoute
  '/t/$tenant_id/settings/billing': typeof TTenant_idSettingsBillingRoute
  '/t/$tenant_id/settings/general': typeof TTenant_idSettingsGeneralRoute
  '/t/$tenant_id/settings/notifications': typeof TTenant_idSettingsNotificationsRoute
  '/t/$tenant_id/approvals/': typeof TTenant_idApprovalsIndexRoute
  '/t/$tenant_id/projects/': typeof TTenant_idProjectsIndexRoute
  '/t/$tenant_id/rules/': typeof TTenant_idRulesIndexRoute
  '/t/$tenant_id/projects/$project_id/api-keys': typeof TTenant_idProjectsProject_idApiKeysRoute
  '/t/$tenant_id/rules/$rule_id/edit': typeof TTenant_idRulesRule_idEditRoute
  '/t/$tenant_id/projects/$project_id/': typeof TTenant_idProjectsProject_idIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-team'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/t/$tenant_id'
    | '/invite/$token'
    | '/t/$tenant_id/analytics'
    | '/t/$tenant_id/dashboard'
    | '/t/$tenant_id/team'
    | '/t/$tenant_id/approvals/$request_id'
    | '/t/$tenant_id/projects/new'
    | '/t/$tenant_id/rules/new'
    | '/t/$tenant_id/settings/account'
    | '/t/$tenant_id/settings/billing'
    | '/t/$tenant_id/settings/general'
    | '/t/$tenant_id/settings/notifications'
    | '/t/$tenant_id/approvals/'
    | '/t/$tenant_id/projects/'
    | '/t/$tenant_id/rules/'
    | '/t/$tenant_id/projects/$project_id/api-keys'
    | '/t/$tenant_id/rules/$rule_id/edit'
    | '/t/$tenant_id/projects/$project_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-team'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/t/$tenant_id'
    | '/invite/$token'
    | '/t/$tenant_id/analytics'
    | '/t/$tenant_id/dashboard'
    | '/t/$tenant_id/team'
    | '/t/$tenant_id/approvals/$request_id'
    | '/t/$tenant_id/projects/new'
    | '/t/$tenant_id/rules/new'
    | '/t/$tenant_id/settings/account'
    | '/t/$tenant_id/settings/billing'
    | '/t/$tenant_id/settings/general'
    | '/t/$tenant_id/settings/notifications'
    | '/t/$tenant_id/approvals'
    | '/t/$tenant_id/projects'
    | '/t/$tenant_id/rules'
    | '/t/$tenant_id/projects/$project_id/api-keys'
    | '/t/$tenant_id/rules/$rule_id/edit'
    | '/t/$tenant_id/projects/$project_id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/create-team'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/t/$tenant_id'
    | '/_auth/invite/$token'
    | '/t/$tenant_id/analytics'
    | '/t/$tenant_id/dashboard'
    | '/t/$tenant_id/team'
    | '/t/$tenant_id/approvals/$request_id'
    | '/t/$tenant_id/projects/new'
    | '/t/$tenant_id/rules/new'
    | '/t/$tenant_id/settings/account'
    | '/t/$tenant_id/settings/billing'
    | '/t/$tenant_id/settings/general'
    | '/t/$tenant_id/settings/notifications'
    | '/t/$tenant_id/approvals/'
    | '/t/$tenant_id/projects/'
    | '/t/$tenant_id/rules/'
    | '/t/$tenant_id/projects/$project_id/api-keys'
    | '/t/$tenant_id/rules/$rule_id/edit'
    | '/t/$tenant_id/projects/$project_id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CreateTeamRoute: typeof CreateTeamRoute
  TTenant_idRoute: typeof TTenant_idRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant_id': {
      id: '/t/$tenant_id'
      path: '/t/$tenant_id'
      fullPath: '/t/$tenant_id'
      preLoaderRoute: typeof TTenant_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/t/$tenant_id/team': {
      id: '/t/$tenant_id/team'
      path: '/team'
      fullPath: '/t/$tenant_id/team'
      preLoaderRoute: typeof TTenant_idTeamRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/dashboard': {
      id: '/t/$tenant_id/dashboard'
      path: '/dashboard'
      fullPath: '/t/$tenant_id/dashboard'
      preLoaderRoute: typeof TTenant_idDashboardRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/analytics': {
      id: '/t/$tenant_id/analytics'
      path: '/analytics'
      fullPath: '/t/$tenant_id/analytics'
      preLoaderRoute: typeof TTenant_idAnalyticsRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/t/$tenant_id/rules/': {
      id: '/t/$tenant_id/rules/'
      path: '/rules'
      fullPath: '/t/$tenant_id/rules/'
      preLoaderRoute: typeof TTenant_idRulesIndexRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/projects/': {
      id: '/t/$tenant_id/projects/'
      path: '/projects'
      fullPath: '/t/$tenant_id/projects/'
      preLoaderRoute: typeof TTenant_idProjectsIndexRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/approvals/': {
      id: '/t/$tenant_id/approvals/'
      path: '/approvals'
      fullPath: '/t/$tenant_id/approvals/'
      preLoaderRoute: typeof TTenant_idApprovalsIndexRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/settings/notifications': {
      id: '/t/$tenant_id/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/t/$tenant_id/settings/notifications'
      preLoaderRoute: typeof TTenant_idSettingsNotificationsRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/settings/general': {
      id: '/t/$tenant_id/settings/general'
      path: '/settings/general'
      fullPath: '/t/$tenant_id/settings/general'
      preLoaderRoute: typeof TTenant_idSettingsGeneralRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/settings/billing': {
      id: '/t/$tenant_id/settings/billing'
      path: '/settings/billing'
      fullPath: '/t/$tenant_id/settings/billing'
      preLoaderRoute: typeof TTenant_idSettingsBillingRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/settings/account': {
      id: '/t/$tenant_id/settings/account'
      path: '/settings/account'
      fullPath: '/t/$tenant_id/settings/account'
      preLoaderRoute: typeof TTenant_idSettingsAccountRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/rules/new': {
      id: '/t/$tenant_id/rules/new'
      path: '/rules/new'
      fullPath: '/t/$tenant_id/rules/new'
      preLoaderRoute: typeof TTenant_idRulesNewRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/projects/new': {
      id: '/t/$tenant_id/projects/new'
      path: '/projects/new'
      fullPath: '/t/$tenant_id/projects/new'
      preLoaderRoute: typeof TTenant_idProjectsNewRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/approvals/$request_id': {
      id: '/t/$tenant_id/approvals/$request_id'
      path: '/approvals/$request_id'
      fullPath: '/t/$tenant_id/approvals/$request_id'
      preLoaderRoute: typeof TTenant_idApprovalsRequest_idRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/projects/$project_id/': {
      id: '/t/$tenant_id/projects/$project_id/'
      path: '/projects/$project_id'
      fullPath: '/t/$tenant_id/projects/$project_id/'
      preLoaderRoute: typeof TTenant_idProjectsProject_idIndexRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/rules/$rule_id/edit': {
      id: '/t/$tenant_id/rules/$rule_id/edit'
      path: '/rules/$rule_id/edit'
      fullPath: '/t/$tenant_id/rules/$rule_id/edit'
      preLoaderRoute: typeof TTenant_idRulesRule_idEditRouteImport
      parentRoute: typeof TTenant_idRoute
    }
    '/t/$tenant_id/projects/$project_id/api-keys': {
      id: '/t/$tenant_id/projects/$project_id/api-keys'
      path: '/projects/$project_id/api-keys'
      fullPath: '/t/$tenant_id/projects/$project_id/api-keys'
      preLoaderRoute: typeof TTenant_idProjectsProject_idApiKeysRouteImport
      parentRoute: typeof TTenant_idRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TTenant_idRouteChildren {
  TTenant_idAnalyticsRoute: typeof TTenant_idAnalyticsRoute
  TTenant_idDashboardRoute: typeof TTenant_idDashboardRoute
  TTenant_idTeamRoute: typeof TTenant_idTeamRoute
  TTenant_idApprovalsRequest_idRoute: typeof TTenant_idApprovalsRequest_idRoute
  TTenant_idProjectsNewRoute: typeof TTenant_idProjectsNewRoute
  TTenant_idRulesNewRoute: typeof TTenant_idRulesNewRoute
  TTenant_idSettingsAccountRoute: typeof TTenant_idSettingsAccountRoute
  TTenant_idSettingsBillingRoute: typeof TTenant_idSettingsBillingRoute
  TTenant_idSettingsGeneralRoute: typeof TTenant_idSettingsGeneralRoute
  TTenant_idSettingsNotificationsRoute: typeof TTenant_idSettingsNotificationsRoute
  TTenant_idApprovalsIndexRoute: typeof TTenant_idApprovalsIndexRoute
  TTenant_idProjectsIndexRoute: typeof TTenant_idProjectsIndexRoute
  TTenant_idRulesIndexRoute: typeof TTenant_idRulesIndexRoute
  TTenant_idProjectsProject_idApiKeysRoute: typeof TTenant_idProjectsProject_idApiKeysRoute
  TTenant_idRulesRule_idEditRoute: typeof TTenant_idRulesRule_idEditRoute
  TTenant_idProjectsProject_idIndexRoute: typeof TTenant_idProjectsProject_idIndexRoute
}

const TTenant_idRouteChildren: TTenant_idRouteChildren = {
  TTenant_idAnalyticsRoute: TTenant_idAnalyticsRoute,
  TTenant_idDashboardRoute: TTenant_idDashboardRoute,
  TTenant_idTeamRoute: TTenant_idTeamRoute,
  TTenant_idApprovalsRequest_idRoute: TTenant_idApprovalsRequest_idRoute,
  TTenant_idProjectsNewRoute: TTenant_idProjectsNewRoute,
  TTenant_idRulesNewRoute: TTenant_idRulesNewRoute,
  TTenant_idSettingsAccountRoute: TTenant_idSettingsAccountRoute,
  TTenant_idSettingsBillingRoute: TTenant_idSettingsBillingRoute,
  TTenant_idSettingsGeneralRoute: TTenant_idSettingsGeneralRoute,
  TTenant_idSettingsNotificationsRoute: TTenant_idSettingsNotificationsRoute,
  TTenant_idApprovalsIndexRoute: TTenant_idApprovalsIndexRoute,
  TTenant_idProjectsIndexRoute: TTenant_idProjectsIndexRoute,
  TTenant_idRulesIndexRoute: TTenant_idRulesIndexRoute,
  TTenant_idProjectsProject_idApiKeysRoute:
    TTenant_idProjectsProject_idApiKeysRoute,
  TTenant_idRulesRule_idEditRoute: TTenant_idRulesRule_idEditRoute,
  TTenant_idProjectsProject_idIndexRoute:
    TTenant_idProjectsProject_idIndexRoute,
}

const TTenant_idRouteWithChildren = TTenant_idRoute._addFileChildren(
  TTenant_idRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CreateTeamRoute: CreateTeamRoute,
  TTenant_idRoute: TTenant_idRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
